
image: python:latest

tests:
  stage: test
  script:
    - cd tests
    - python3 -m pip install -r test_requirements.txt
    - pytest --cov=../pytools
    - coverage xml
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: tests/coverage.xml
