name: pymedeas_dev
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pysd=3.0.0
  - matplotlib
  - dacite
  - pyinstaller
  - pytest
  - pytest-cov
  - pytest-xdist
  - pytest-mock
  - coverage

